# Generated by Django 5.1.7 on 2025-05-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book_Unit',
            new_name='BookUnit',
        ),
        migrations.RenameModel(
            old_name='Borrows',
            new_name='Borrow',
        ),
        migrations.AddConstraint(
            model_name='author',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name'), name='unique_author'),
        ),
    ]
